# Generated by Django 4.2.3 on 2023-07-18 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True)),
                ('category_id', models.PositiveSmallIntegerField(auto_created=True)),
                ('category_title', models.CharField(blank=True, max_length=64, null=True)),
                ('order_id', models.PositiveSmallIntegerField(null=True)),
                ('user_accesses', models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order_id'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True)),
                ('item_id', models.PositiveSmallIntegerField(auto_created=True)),
                ('item_title', models.CharField(blank=True, max_length=64, null=True)),
                ('item_description', models.CharField(blank=True, max_length=256, null=True)),
                ('order_id', models.PositiveSmallIntegerField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category__order_id', 'order_id'],
            },
        ),
    ]
