# Generated by Django 4.2.3 on 2023-07-18 09:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='user_accesses',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
